<a href="https://colab.research.google.com/github/gorzanskik-ai/binary-classification-movie-reviews/blob/main/movie_reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True, edgeitems=10, linewidth=1000, formatter=dict(float=lambda x: f'{x:.2f}'))
sklearn.__version__

'1.0.2'

In [ ]:
!wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/movie_reviews.zip

--2022-06-02 07:14:44--  https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/movie_reviews.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4004848 (3.8M) [application/zip]
Saving to: ‘movie_reviews.zip’

movie_reviews.zip   100%[===================>]   3.82M  --.-KB/s    in 0.07s   

2022-06-02 07:14:44 (52.3 MB/s) - ‘movie_reviews.zip’ saved [4004848/4004848]



In [ ]:
!unzip -q movie_reviews.zip

In [ ]:
!pwd
!ls

/content
movie_reviews  movie_reviews.zip  sample_data


In [ ]:
from sklearn.datasets import load_files

raw_movie = load_files('movie_reviews')
movie = raw_movie.copy()
movie.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

Ekspolracja danych

In [ ]:
X = movie['data']
y = movie['target']

In [ ]:
X[:10]

[b"arnold schwarzenegger has been an icon for action enthusiasts , since the late 80's , but lately his films have been very sloppy and the one-liners are getting worse . \nit's hard seeing arnold as mr . freeze in batman and robin , especially when he says tons of ice jokes , but hey he got 15 million , what's it matter to him ? \nonce again arnold has signed to do another expensive blockbuster , that can't compare with the likes of the terminator series , true lies and even eraser . \nin this so called dark thriller , the devil ( gabriel byrne ) has come upon earth , to impregnate a woman ( robin tunney ) which happens every 1000 years , and basically destroy the world , but apparently god has chosen one man , and that one man is jericho cane ( arnold himself ) . \nwith the help of a trusty sidekick ( kevin pollack ) , they will stop at nothing to let the devil take over the world ! \nparts of this are actually so absurd , that they would fit right in with dogma . \nyes , the film is

In [ ]:
y[:10]

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
movie['target_names']

['neg', 'pos']

In [ ]:
movie['filenames'][:2]

array(['movie_reviews/neg/cv405_21868.txt', 'movie_reviews/pos/cv190_27052.txt'], dtype='<U33')

Podział danych na treningowe i testowe

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

print(f'X_train: {len(X_train)}')
print(f'X_test: {len(X_test)}')

X_train: 1500
X_test: 500


In [ ]:
X_train[0]

b'unzipped is a cinematic portrait of isaac mizrahi , an artist whose palette is fabric . \nostensibly , the film is a documentary , but use of that term requires stretching its meaning . \nmany scenes appear staged , and a great deal of cutting-and-pasting has been done in the editing room . \nthe cinema verite effect is a conceit -- genuine spontaneity is at a premium , and everyone is aware of and playing to the camera ( especially would-be actresses like cindy crawford ) . \ndirector douglas keeve ( who was mizrahi\'s lover at the time ) freely admits that he " couldn\'t care less about the truth " but was more interested in capturing " the spirit and love in isaac and in fashion . " \ndespite violating nearly every rule of " legitimate " documentary film making , however , unzipped is a remarkably enjoyable piece of entertainment . \nwhile it sheds only a little light on the behind-the-scenes world of the fashion industry , it presents a fascinating , if incomplete , picture of de

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (1500, 3000)
X_test shape: (500, 3000)


In [ ]:
df = pd.DataFrame(data=tfidf.fit_transform(X).toarray(),
                  columns=tfidf.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning:

Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.



000   10       100   12   13        15   17  1993  1994  1995  ...  \
0     0.000000  0.0  0.000000  0.0  0.0  0.050184  0.0   0.0   0.0   0.0  ...   
1     0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
2     0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
3     0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
4     0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
...        ...  ...       ...  ...  ...       ...  ...   ...   ...   ...  ...   
1995  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
1996  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
1997  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
1998  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   
1999  0.084187  0.0  0.044319  0.0  0.0  0.000000  0.0   0.0   0.0   0.0  ...   

          yes       yet      york       you     young  younger      your  \
0     0.03675  0.000000  0.000000  0.074260  0.000000      0.0  0.051600   
1     0.00000  0.000000  0.000000  0.015232  0.000000      0.0  0.000000   
2     0.00000  0.000000  0.000000  0.139719  0.036215      0.0  0.000000   
3     0.00000  0.000000  0.000000  0.022860  0.000000      0.0  0.000000   
4     0.00000  0.000000  0.000000  0.000000  0.000000      0.0  0.000000   
...       ...       ...       ...       ...       ...      ...       ...   
1995  0.00000  0.022857  0.000000  0.000000  0.022286      0.0  0.021337   
1996  0.00000  0.000000  0.000000  0.000000  0.000000      0.0  0.000000   
1997  0.02517  0.000000  0.027138  0.020344  0.000000      0.0  0.035341   
1998  0.00000  0.000000  0.000000  0.000000  0.000000      0.0  0.000000   
1999  0.00000  0.000000  0.036037  0.000000  0.000000      0.0  0.000000   

      yourself  youth  zero  
0          0.0    0.0   0.0  
1          0.0    0.0   0.0  
2          0.0    0.0   0.0  
3          0.0    0.0   0.0  
4          0.0    0.0   0.0  
...        ...    ...   ...  
1995       0.0    0.0   0.0  
1996       0.0    0.0   0.0  
1997       0.0    0.0   0.0  
1998       0.0    0.0   0.0  
1999       0.0    0.0   0.0  

[2000 rows x 3000 columns]

Model

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()
params = {'alpha': np.arange(0.1, 5, 0.1),
          'fit_prior': [True, False]}

grid_search = GridSearchCV(estimator=classifier, param_grid=params, scoring='accuracy', cv=3)
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'alpha': 0.4, 'fit_prior': False}

In [ ]:
classifier = MultinomialNB(alpha=0.4, fit_prior=False)
classifier.fit(X_train, y_train)
classifier.score(X_test, y_test)

0.808

Ocena modelu

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[198,  42],
       [ 54, 206]])

In [ ]:
import plotly.figure_factory as ff

def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['negative', 'positive'], index=['positive', 'negative'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=['negative', 'positive']))

              precision    recall  f1-score   support

    negative       0.79      0.82      0.80       240
    positive       0.83      0.79      0.81       260

    accuracy                           0.81       500
   macro avg       0.81      0.81      0.81       500
weighted avg       0.81      0.81      0.81       500



Predykcja na podstawie modelu

In [ ]:
new_reviews = ['It was awesome! Very interesting story.',
               'I cannot recommend this film. Short and awful.',
               'Very long and boring. Don\'t waste your time.',
               'Well-organized and quite interesting.']

new_reviews_tfidf = tfidf.transform(new_reviews)
new_reviews_tfidf

<4x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [ ]:
new_reviews_tfidf.toarray()

array([[0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, ..., 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, ..., 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, ..., 0.00, 0.00, 0.00, 0.00, 0.00, 0.34, 0.00, 0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, ..., 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]])

In [ ]:
new_reviews_pred = classifier.predict(new_reviews_tfidf)
new_reviews_pred

array([1, 0, 0, 1])

In [ ]:
new_reviews_prob = classifier.predict_proba(new_reviews_tfidf)
new_reviews_prob

array([[0.47, 0.53],
       [0.67, 0.33],
       [0.82, 0.18],
       [0.42, 0.58]])

In [ ]:
np.argmax(new_reviews_prob, axis=1)

array([1, 0, 0, 1])

In [ ]:
movie['target_names']

['neg', 'pos']

In [ ]:
for review, target, prob in zip(new_reviews, new_reviews_pred, new_reviews_prob):
    print(f"{review} -> {movie['target_names'][target]} -> {prob[target]:.4f}")

It was awesome! Very interesting story. -> pos -> 0.5332
I cannot recommend this film. Short and awful. -> neg -> 0.6718
Very long and boring. Don't waste your time. -> neg -> 0.8172
Well-organized and quite interesting. -> pos -> 0.5757
